export const createUser = async (req,res)=>{
    try {
        
    } catch (error) {
        console.log("error in creating user",error);
    }
}

export const deleteUser = async (req,res)=>{
    try{

    }catch(error){
        console.log("error in deleting user",error);
    }
}

export const banOrUnbanUser = async (req,res)=>{
    try {
        
    } catch (error) {
        console.log("error in banning user",error);
    }
}

export const promoteUser = async (req,res)=>{
    try {
        
    } catch (error) {
        console.log("error in promoting user",error);
    }
}