export const createPost = async(req,res)=>{
    try{

    }catch(error){
        console.log("error in creating post",error);
    }
}
export const deletePost = async (req,res)=>{
    try {
        
    } catch (error) {
        console.log("error in deleting post",error);
    }
}

export const updatePost = async (req,res)=>{
    try {
        
    } catch (error) {
        console.log("error in updating post",error);
    }
}

export const flagOrUnflagPost = async(req,res)=>{
    try {
        
    } catch (error) {
        console.log("error in flag post",error);
    }
}

export const approvePost = async (req, res)=>{
    try {
        
    } catch (error) {
        console.log("error in approving post",error);
    }
}
export const rejectPost = async (req,res)=>{
    try {
        
    } catch (error) {
        console.log("error in rejecting post",error);
    }
}